In [ ]:
from datasets import load_dataset

dataset = load_dataset("CShorten/ML-ArXiv-Papers")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

ML-Arxiv-Papers.csv:   0%|          | 0.00/147M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [ ]:
import pandas as pd
df = dataset["train"].to_pandas()
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [ ]:
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."
117591,4999,NaN,Adapting and Evaluating Influence-Estimation M...,Influence estimation analyzes how changes to t...

In [ ]:
df = df[['title', 'abstract']]
df=df.head(50000)
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [ ]:
df["paper_text"] = df["title"] + " " + df["abstract"]
df

,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
49995,"See, Attend and Brake: An Attention-based Sali...",Visual perception is the most critical input...,"See, Attend and Brake: An Attention-based Sali..."
49996,SNIFF: Reverse Engineering of Neural Networks ...,Neural networks have been shown to be vulner...,SNIFF: Reverse Engineering of Neural Networks ...
49997,Beyond Dropout: Feature Map Distortion to Regu...,Deep neural networks often consist of a grea...,Beyond Dropout: Feature Map Distortion to Regu...
49998,A study of resting-state EEG biomarkers for de...,Background: Depression has become a major he...,A study of resting-state EEG biomarkers for de...
49999,Performance Analysis of Combine Harvester usin...,Novel applications of artificial intelligenc...,Performance Analysis of Combine Harvester usin...

In [ ]:
df['paper_text'].head()

0    Learning from compressed observations   The pr...
1    Sensor Networks with Random Links: Topology De...
2    The on-line shortest path problem under partia...
3    A neural network approach to ordinal regressio...
4    Parametric Learning and Monte Carlo Optimizati...
Name: paper_text, dtype: object

In [ ]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [ ]:
print(df['paper_text'].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [ ]:
sample_text = df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

In [ ]:
df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
df["paper_text"] = df["paper_text"].str.strip()

In [ ]:
sample_text = df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [ ]:
embedding = model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [ ]:
embedding[:56]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474,
        0.05692544,  0.0201578 ,  0.0258311 ,  0.0321703 ,  0.10513764,
       -0.09676763,  0.02700802, -0.0234509 , -0.04549678, -0.01013699,
       -0.01794855, -0.04814427,  0.01077652, -0.03759069,  0.01943481,
        0.03715189,  0.02967844,  0.04330941,  0.04373213,  0.03704866,
       -0.00182594,  0.00455183, -0.00799067,  0.03037368, -0.014378  ,
        0.03795147,  0.0595916 , -0.02583356, -0.06521576,  0.05900268,
       -0.02107134,  0.07359422, -0.05720106,  0.00294061,  0.00767515,
       -0.0333416 ], dtype=float32)

In [ ]:
sample_embedding = model.encode(
    df["paper_text"].head(5).to_list()
)

print(sample_embedding.shape)

(5, 384)

In [ ]:
import sklearn
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity([sample_embedding[0]], [sample_embedding[0]])
print(similarity)

[[1.0000001]]

In [ ]:
similarity = cosine_similarity(sample_embedding[0].reshape(1, -1), sample_embedding[1].reshape(1, -1))
print(similarity)

[[0.36625272]]

In [ ]:
# 1. Run the import again to fix the NameError
from sklearn.metrics.pairwise import cosine_similarity

# 2. Run your loop
for i in range(1, 5):
    sim = cosine_similarity(sample_embedding[0].reshape(1, -1), sample_embedding[i].reshape(1, -1))
    print(f"Similarity with Paper {i}: {sim[0][0]}")

Similarity with Paper 1: 0.36625272035598755
Similarity with Paper 2: 0.33522844314575195
Similarity with Paper 3: 0.1550510823726654
Similarity with Paper 4: 0.37421533465385437

In [ ]:
embedding = model.encode(df["paper_text"].to_list(), batch_size=32, show_progress_bar=True)

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

In [ ]:
import numpy as np
import os
index_path = "../data/arxiv_embeddings.npy"

if os.path.exists(index_path):
    print("Loading saved embeddings")
    embeddings = np.load(index_path)
else:
    print("Generating embeddings")
    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save(index_path, embeddings)
    print("Embeddings saved successfully!")
# This saves your 26-minute calculation instantly to a file in your folder
np.save(index_path, embedding)

print("Embeddings successfully saved to disk!")

In [ ]:
# Save the cleaned dataframe so we can map the math back to actual paper titles
df.to_csv("../data/cleaned_arxiv_papers.csv", index=False)
print("Cleaned DataFrame saved successfully!")

In [ ]:
import pandas as pd

print("Total Papers:",len(df))
print("Columns:",df.columns)

df.info()

In [ ]:
import matplotlib.pyplot as plt

missing=df.isnull().sum()

plt.figure(figsize=(8,5))
plt.bar(missing.index,missing.values)
plt.xticks(rotation=45)
plt.show()

In [ ]:
df["abstract_length"]=df["abstract"].apply(
    lambda x: len(str(x).split())
)

plt.hist(df["abstract_length"],bins=50)

plt.xlabel("Word Count")
plt.ylabel("Number of Papers")

plt.show()

In [ ]:
from collections import Counter

all_words=' '.join(
    df['abstract'].astype(str)
).split()

common=Counter(all_words)

print(
common.most_common(20)
)

In [ ]:
!pip install wordcloud

In [ ]:
from wordcloud import WordCloud
import matplotlib.pyplot as plt

text=' '.join(
df['abstract'].astype(str)
)

wc=WordCloud().generate(text)

plt.imshow(wc)

plt.axis("off")

plt.show()

In [ ]:
from sklearn.decomposition import PCA

pca=PCA(n_components=2)

reduced=pca.fit_transform(
embeddings[:1000]
)

plt.scatter(
reduced[:,0],
reduced[:,1]
)

plt.show()

In [ ]:
from sklearn.manifold import TSNE

tsne=TSNE(
n_components=2,
random_state=42
)

reduced=tsne.fit_transform(
embeddings[:1000]
)

plt.scatter(
reduced[:,0],
reduced[:,1]
)

plt.show()

In [ ]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

words=' '.join(
df['abstract'].astype(str)
).split()

filtered_words=[
word.lower()
for word in words
if word.lower() not in ENGLISH_STOP_WORDS
]

common=Counter(filtered_words)

print(
common.most_common(20)
)

In [ ]:
df["abstract_length"]=df[
    "abstract"
].apply(
    lambda x: len(
        str(x).split()
    )
)

plt.figure(figsize=(8,5))

plt.hist(
    df["abstract_length"],
    bins=50
)

plt.xlabel(
    "Number of Words"
)

plt.ylabel(
    "Paper Count"
)

plt.show()

In [ ]:
df["title_length"]=df[
    "title"
].apply(
    lambda x: len(
        str(x).split()
    )
)

plt.scatter(
    df["title_length"],
    df["abstract_length"]
)

plt.xlabel(
    "Title Length"
)

plt.ylabel(
    "Abstract Length"
)

plt.show()

In [ ]:
from sklearn.cluster import KMeans

kmeans=KMeans(
    n_clusters=5,
    random_state=42
)

clusters=kmeans.fit_predict(
    embeddings[:1000]
)

plt.scatter(
    reduced[:,0],
    reduced[:,1],
    c=clusters
)

plt.show()

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

sample=10

similarities=cosine_similarity(
    [embeddings[sample]],
    embeddings
)

top=similarities.argsort()[0][-6:-1]

for i in top:

    print(
        df.iloc[i]["title"]
    )